config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"

  get "/selecao_estado", to: "deputados#selecao_estado"
  get "/deputados", to: "deputados#index"

  resources :deputados, only: [:index, :show]

  resources :despesas do
    collection do
      get :upload
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deputado.rb
class Deputado < ApplicationRecord
  has_many :despesas, dependent: :destroy

  validates :ide_cadastro, uniqueness: true, presence: true, numericality: { only_integer: true }
  validates :nome, presence: true
  
  extend EnumerateIt
  has_enumeration_for :partido, with: PartidoEnum
  
  def self.lista_partidos
    PartidoEnum.list
  end
end

app/models/despesa.rb
class Despesa < ApplicationRecord
  belongs_to :deputado

  validates :ide_documento, uniqueness: true, presence: true

  #Em vez de fazer a consulta diretamente na view, podemos usar um método no model Despesa
  def self.anos_disponiveis
    select("DISTINCT EXTRACT(YEAR FROM data_emissao) AS ano")
      .where("EXTRACT(YEAR FROM data_emissao) > 2000")
      .map { |d| d.ano.to_i }
      .sort
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deputados_controller.rb
class DeputadosController < ApplicationController
  def selecao_estado
  end

  def index
    if params[:estado].present?
      @deputados = Deputado
        .select("deputados.*, COALESCE(SUM(despesas.valor_liquido), 0) AS total_despesas, MAX(valor_liquido) as maior_despesa")
        .joins("LEFT JOIN despesas ON despesas.deputado_id = deputados.id")
        .where(estado: params[:estado])
        .group("deputados.id")
        .order("total_despesas DESC")

      @deputados = @deputados.where("EXTRACT(YEAR FROM despesas.data_emissao) = ?", params[:ano].to_i) if params[:ano].present?

      @deputados = @deputados.where("LOWER(nome) LIKE ?", "%#{params[:nome].downcase}%") if params[:nome].present?

      @deputados = @deputados.where(partido: params[:partido]) if params[:partido].present?

      @deputados = @deputados.page(params[:page]).per(10)
    else
      flash[:alert] = "Por favor, selecione um estado para continuar."
      redirect_to root_path
    end
  end

  def show
    @deputado = Deputado.find(params[:id])

    @despesas = @deputado.despesas.order(valor_liquido: :desc)
    @despesas = @despesas.where("EXTRACT(YEAR FROM despesas.data_emissao) = ?", params[:ano].to_i) if params[:ano].present?
    @maior_despesa = @despesas.first
    @total_despesas = @despesas.sum(:valor_liquido)
    
    @despesas = @despesas.page(params[:page]).per(10)
  end
end

app/controllers/despesas_controller.rb
require 'csv'

class DespesasController < ApplicationController
  def upload
  end

  def import
    if params[:arquivo].present?
      resultado = DespesaImportService.new(params[:arquivo]).processar
      redirect_to root_path, notice: "Importação concluída!! #{resultado[:sucesso]} registros importados. #{resultado[:erros]} erros."
    else
      redirect_to upload_despesas_path, alert: "Por gentileza, selecione um arquivo CSV!!"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @total_deputados = Deputado.count
    @total_despesas = Despesa.count
    @gastos_totais = Despesa.sum(:valor_liquido)

    @exercicios_disponiveis = Despesa
                              .select("DISTINCT EXTRACT(YEAR FROM data_emissao) AS ano")
                              .where("EXTRACT(YEAR FROM data_emissao) > 2000")
                              .map { |d| d.ano.to_i }
                              .sort
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deputados/index.html.erb
<h1 class="text-center my-4">Deputados do Estado <%= params[:estado] %></h1>

<div class="container">
    <div class="mb-4">
        <%= form_with url: deputados_path, method: :get, local: true, class: "row g-3 align-items-end" do %>
            <%= hidden_field_tag :estado, params[:estado] %>

            <div class="row g-3 justify-content-center">
                <div class="col-md-4">
                    <%= label_tag :nome, "Nome do Deputado", class: "form-label" %>
                    <%= text_field_tag :nome, params[:nome], class: "form-control" %>
                </div>

                <div class="col-md-3">
                    <%= label_tag :partido, "Partido", class: "form-label" %>
                    <%= select_tag :partido, options_for_select(Deputado.lista_partidos, params[:partido]), class: "form-select" %>
                </div>

                <div class="col-md-3">
                    <%= label_tag :ano, "Ano da Despesa", class: "form-label" %>
                    <%= select_tag :ano, 
                        options_for_select(Despesa.anos_disponiveis, params[:ano]), 
                        include_blank: "Todos os exercícios", class: "form-select" %> 
                </div>
            </div>

            <div class="row mt-3 justify-content-center">
                <div class="col-md-3 d-flex gap-2">
                    <%= submit_tag "Filtrar", class: "btn btn-primary w-100" %>
                    <%= link_to "Limpar", deputados_path(estado: params[:estado]), class: "btn btn-secondary w-100" %>
                </div>
            </div>
        <% end %>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-bordered align-middle">
            <thead class="table-dark text-center">
                <tr>
                    <th>Foto</th>
                    <th>Nome</th>
                    <th>Partido</th>
                    <th>Estado</th>
                    <th>Maior despesa</th>
                    <th>Total de Despesa</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody class="text-center">
                <% @deputados.each do |deputados| %>
                    <tr>
                        <td>
                            <img src="http://www.camara.leg.br/internet/deputado/bandep/<%= deputados.ide_cadastro %>.jpg" 
                                alt="Foto de <%= deputados.nome %>" class="rounded-circle" width="50" height="50">
                        </td>
                        <td><%= deputados.nome %></td>
                        <td><%= deputados.partido %></td>
                        <td><%= deputados.estado %></td>
                        <td>R$ <%= number_to_currency(deputados.maior_despesa, unit: "", separator: ",", delimiter: ".") %></td>
                        <td>R$ <%= number_to_currency(deputados.total_despesas, unit: "", separator: ",", delimiter: ".") %></td>
                        <td><%= link_to "Detalhes", deputado_path(deputados, ano: params[:ano]), class: "btn btn-info btn-sm" %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-center my-4">
        <%= paginate @deputados %>
    </div>

    <div class="d-flex justify-content-center gap-3 mt-4">
        <%= link_to "Voltar", selecao_estado_path, class: "btn btn-secondary" %>
        <%= link_to "Página Inicial", root_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/deputados/selecao_estado.html.erb
<h1 class="text-center my-4">Selecione um Estado para continuar</h1>

<div class="d-flex justify-content-center">
    <%= form_with url: deputados_path, method: :get, local: true, class: "w-50" do %>
        <div class="mb-3">
            <label for="estado" class="form-label">Estado:</label>
            <%= select_tag :estado, 
                options_for_select(Deputado.distinct.pluck(:estado).sort), 
                prompt: "Escolha um estado",
                class: "form-select" %>
        </div>

        <div class="text-center">
            <%= submit_tag "Filtrar Deputados", class: "btn btn-primary" %>
            <%= link_to "Voltar", root_path, class: "btn btn-secondary" %>
        </div>
    <% end %>
</div>

app/views/deputados/show.html.erb
<div class="container mt-5">
    <h1 class="text-center">Detalhes do Deputado</h1>

    <div class="card p-4 shadow-sm">
        <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <img src="http://www.camara.leg.br/internet/deputado/bandep/<%= @deputado.ide_cadastro %>.jpg" 
                    alt="Foto de <%= @deputado.nome %>" class="rounded-circle me-3" width="100" height="100">
                <div>
                    <h3><%= @deputado.nome %></h3>
                    <p>Partido: <%= @deputado.partido %></p>
                    <p>Estado: <%= @deputado.estado %></p>
                    <p><strong>Total de Despesas:</strong> R$ <%= number_to_currency(@total_despesas, unit: "", separator: ",", delimiter: ".") %></p>
                </div>
            </div>
            <div class="ms-auto text-center">
                <% if params[:ano].present? %>
                    <p>Exibindo despesas do Exercício:</p>
                    <p><strong class="badge bg-secondary fs-5 px-3 py-2"><%= params[:ano] %></strong></p>
                <% end %>
            </div>
        </div>
    </div>

    <h3 class="mt-4">Lista de Despesas</h3>
    <table class="table table-striped mt-3">
        <thead class="table-dark text-center">
            <tr>
                <th>Data</th>
                <th>Fornecedor</th>
                <th>Valor</th>
                <th>Nota Fiscal</th>
            </tr>
        </thead>
        <tbody class="text-center">
            <% @despesas.each do |despesa| %>
                <tr class="<%= 'table-warning' if despesa == @maior_despesa %>">
                    <td><%= despesa.data_emissao.strftime("%d/%m/%Y") %></td>
                    <td><%= despesa.fornecedor %></td>
                    <td>R$ <%= number_to_currency(despesa.valor_liquido, unit: "", separator: ",", delimiter: ".") %></td>
                    <td>
                        <% if despesa.nota_fiscal_url.present? %>
                            <a href="<%= despesa.nota_fiscal_url %>" target="_blank" class="btn btn-primary btn-sm">Ver Nota</a>
                        <% else %>
                            <span class="text-muted">Não disponível</span>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <div class="d-flex justify-content-center my-4">
        <%= paginate @despesas %>
    </div>

    <div class="text-center mt-4">
        <%= link_to "Voltar", deputados_path(estado: @deputado.estado), class: "btn btn-secondary" %>
        <%= link_to "Página Inicial", root_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/despesas/upload.html.erb
<h1 class="text-center my-4">Importar despesas</h1>

<div class="d-flex justify-content-center">
    <%= form_with url: import_despesas_path, multipart: true, method: :post, class: "w-50" do %>
        <div class="mb-3">
            <label for="arquivo" class="form-label">Selecione um arquivo CSV:</label>
           <%= file_field_tag :arquivo, class: "form-control", accept: ".csv" %>
        </div>

        <div class="text-center">
            <%= submit_tag "Importar", class: "btn btn-success" %>
            <%= link_to "Início", root_path, class: "btn btn-secondary" %>
        </div>
    <% end %>
</div>

app/views/home/index.html.erb
<div class="container mt-5">
    <h1 class="text-center mb-4">Bem-Vindo ao Sistema de Consulta de Deputados</h1>

    <p class="lead text-center">
        Este sistema permite consultar informações sobre deputados deferais e suas despesas parlamentares.
    </p>

    <p class="lead text-center">
        Navegue pelos botões abaixo ou na barra de navegação acima:
    </p>

    <div class="text-center my-4">
        <%= link_to "Consultar Deputados", selecao_estado_path, class: "btn btn-primary btn-lg" %>
        <%= link_to "Importar CSV", upload_despesas_path, class: "btn btn-success btn-lg" %>
    </div>

    <p class="lead text-center">
        Abaixo um resumo dos valores aqui disponíveis:
    </p>

    <div class="row text-center mt-4">
        <div class="col-md-4">
            <div class="card shadow-sm p-3">
                <h3>Total de Deputados</h3>
                <p class="display-5"><%= @total_deputados %></p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm p-3">
                <h3>Total de Despesas</h3>
                <p class="display-5"><%= @total_despesas %></p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm p-3">
                <h3>Gastos Totais</h3>
                <p class="display-5">R$ <%= number_to_currency(@gastos_totais, unit: "", separator: ",", delimiter: ".") %></p>
            </div>
        </div>
    </div>

    <div class="text-center mt-5">
        <h3>Exercícios Disponíveis</h3>
        <p class="lead">As informações presentes nos dados são dos seguintes exercícios:</p>
        <div class="d-flex justify-content-center gap-2 flex-wrap">
            <% if @exercicios_disponiveis.any? %>
             <% @exercicios_disponiveis.each do |ano| %>
                <span class="badge bg-secondary fs-5 px-3 py-2"><%= ano %></span>
            <% end %>
        <% else %>
        <p class="text-muted">Nenhum exercício disponível no momento.</p>
    <% end %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white text-center py-3 mt-3">
    <div class="container">
        <p>&copy; <%= Time.now.year %> Sistema de consulta de Deputados. Todos os direitos reservados</p>
        <p>
            Desenvolvido por <strong>Guilherme Rocha</strong> | 
            <a href="https://www.linkedin.com/in/guilherme-rocha-828701b6/" target="_blank" class="text-white">Contato</a>
        </p>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top shadow">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="<%= root_path %>">
            <img src="/assets/logo.png" alt="Logo" width="40" height="40" class="me-2">
            <span class="fw-bold">Sistema Político</span>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="<%= root_path %>">
                        <i class="fas fa-home"></i> Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= selecao_estado_path %>">
                        <i class="fas fa-users"></i> Consultar Deputados
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= upload_despesas_path %>">
                        <i class="fas fa-file-upload"></i> Importar CSV
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio Backend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render "layouts/navbar" %>

    <% if flash[:alert] %>
      <div class="alert alert-warning">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <main class="flex-shrink-0 flex-grow-1">
      <div class="container mt-3 pt-4">
        <%= yield %>
      </div>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>